global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["10.20.0.10:8085"]
        labels:
          role: app
          node: app-1
      - targets: ["10.20.0.11:8085"]
        labels:
          role: app
          node: app-2

  - job_name: node
    static_configs:
      - targets: ["10.20.0.10:9100"]
        labels:
          role: app
          node: app-1
      - targets: ["10.20.0.11:9100"]
        labels:
          role: app
          node: app-2
      - targets: ["10.20.0.20:9100"]
        labels:
          role: infra
      - targets: ["10.20.0.30:9100"]
        labels:
          role: test
